FROM python:3.9-slim-buster
LABEL maintainer="IKAS"

RUN sed -i "s@http://deb.debian.org@http://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
RUN sed -i 's|security.debian.org/debian-security|mirrors.tuna.tsinghua.edu.cn/debian-security|g' /etc/apt/sources.list
RUN apt update
RUN apt install -y curl gcc default-libmysqlclient-dev

WORKDIR app
COPY requirements requirements
RUN pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple \
    && pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements/development.txt
