version: '3'
services:
  web:
    image: backend:0.1.0
    volumes:
      - web-logs:/app/logs
      - ${LOCAL_STORAGE_PATH}:${LOCAL_STORAGE_PATH}
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5001:5000"
    restart: always
    command: gunicorn
      autoapp:app
      --bind 0.0.0.0:5000
      -w 8
      -t 0
      -k eventlet
      --access-logfile -
      --error-logfile -
  celery_worker:
    image: backend:0.1.0
    volumes:
      - web-logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
    restart: always
    command: celery -A celery_worker.celery worker -l info -P eventlet
  flower:
    image: backend:0.1.0
    volumes:
      - web-logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: celery -A celery_worker.celery flower -l info
    ports:
      - "5555:5555"
  equipment-mock:
    image: backend:0.1.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: python backend/equipment/provider/mock.py
    depends_on:
      - equipment-sio
  equipment-sio:
    image: backend:0.1.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: gunicorn -k eventlet -w 1 backend.equipment.provider.sio_server:app --bind 0.0.0.0:5050
    ports:
      - "5050:5050"
  eap-listener:
    image: backend:0.1.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: python task/listener/eap_listener.py
  ama-listener:
    image: backend:0.1.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: python task/ama/log_consumer.py
  backend_xyn_mq:
    image: backend:0.1.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: python task/xyn_poc/flow_task_producer.py
  backend_parameter_log:
    image: backend:0.1.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    restart: always
    command: python task/backend/parameter_log.py

volumes:
  web-logs:
networks:
  default:
    external:
      name: backend-backend
