version: '3'
services:
  web:
    image: mini_app_bac:latest
    volumes:
      - web-logs:/app/logs
      - ${LOCAL_STORAGE_PATH}:${LOCAL_STORAGE_PATH}
      - /var/www/images:/var/www/images  # 添加物理机目录挂载
      - /opt/dev/apps/backend/mini_code:/app  # 挂载代码目录到容器的/app目录


    env_file:
      - .env_jj
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8006:5000"
    restart: always
    command: gunicorn
      autoapp:app
      --bind 0.0.0.0:5000
      -w 8
      -t 0
      -k eventlet
      --access-logfile -
      --error-logfile -
  celery_worker:
    image: mini_app_bac:latest
    volumes:
      - web-logs:/app/logs
    env_file:
      - .env_jj
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
    restart: always
    command: celery -A celery_worker.celery worker -l info -P eventlet


volumes:
  web-logs:
networks:
  default:
    external:
      name: backend-backend
